// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function LoadState() {
  return window['go']['main']['App']['LoadState']();
}

export function Publish(arg1) {
  return window['go']['main']['App']['Publish'](arg1);
}

export function PushCreature(arg1) {
  return window['go']['main']['App']['PushCreature'](arg1);
}
