// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function GetState():Promise<Array<server.Creature>>;

export function LoadState():Promise<string>;

export function Publish(arg1:Array<server.Creature>):Promise<void>;

export function PushCreature(arg1:Array<server.Creature>):Promise<void>;
